spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/azurian_db
    username: azurian_user
    password: azurian_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: web-crud-springboot-postgresql

server:
  port: 8080
